/**
 * https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes
 */
insert
  into pje.tb_pais (cd_iso, cd_pais, cd_sigla, ds_pais)
values ('004', 'AF', 'AFG', 'Afeganistão')
     , ('710', 'ZA', 'ZAF', 'África do Sul')
     , ('008', 'AL', 'ALB', 'Albânia')
     , ('276', 'DE', 'DEU', 'Alemanha')
     , ('020', 'AD', 'AND', 'Andorra')
     , ('024', 'AO', 'AGO', 'Angola')
     , ('660', 'AI', 'AIA', 'Anguila')
     , ('010', 'AQ', 'ATA', 'Antártida')
     , ('028', 'AG', 'ATG', 'Antígua e Barbuda')
     , ('530', 'AN', 'ANT', 'Antilhas Holandesas')
     , ('682', 'SA', 'SAU', 'Arábia Saudita')
     , ('012', 'DZ', 'DZA', 'Argélia')
     , ('032', 'AR', 'ARG', 'Argentina')
     , ('051', 'AM', 'ARM', 'Arménia')
     , ('533', 'AW', 'ABW', 'Aruba')
     , ('036', 'AU', 'AUS', 'Austrália')
     , ('040', 'AT', 'AUT', 'Áustria')
     , ('031', 'AZ', 'AZE', 'Azerbaijão')
     , ('044', 'BS', 'BHS', 'Baamas')
     , ('048', 'BH', 'BHR', 'Bahrein')
     , ('050', 'BD', 'BGD', 'Bangladesh')
     , ('052', 'BB', 'BRB', 'Barbados')
     , ('056', 'BE', 'BEL', 'Bélgica')
     , ('084', 'BZ', 'BLZ', 'Belize')
     , ('204', 'BJ', 'BEN', 'Benim')
     , ('060', 'BM', 'BMU', 'Bermudas')
     , ('112', 'BY', 'BLR', 'Bielorrússia')
     , ('068', 'BO', 'BOL', 'Bolívia')
     , ('070', 'BA', 'BIH', 'Bósnia-Herzegóvina')
     , ('072', 'BW', 'BWA', 'Botsuana')
     , ('076', 'BR', 'BRA', 'Brasil')
     , ('096', 'BN', 'BRN', 'Brunei')
     , ('100', 'BG', 'BGR', 'Bulgária')
     , ('854', 'BF', 'BFA', 'Burkina Fasso')
     , ('108', 'BI', 'BDI', 'Burundi')
     , ('064', 'BT', 'BTN', 'Butão')
     , ('132', 'CV', 'CPV', 'Cabo Verde')
     , ('120', 'CM', 'CMR', 'Camarões')
     , ('116', 'KH', 'KHM', 'Camboja')
     , ('124', 'CA', 'CAN', 'Canadá')
     , ('398', 'KZ', 'KAZ', 'Cazaquistão')
     , ('148', 'TD', 'TCD', 'Chade')
     , ('152', 'CL', 'CHL', 'Chile')
     , ('156', 'CN', 'CHN', 'China')
     , ('196', 'CY', 'CYP', 'Chipre')
     , ('170', 'CO', 'COL', 'Colômbia')
     , ('178', 'CG', 'COG', 'Congo')
     , ('408', 'KP', 'PRK', 'Coreia do Norte')
     , ('410', 'KR', 'KOR', 'Coreia do Sul')
     , ('384', 'CI', 'CIV', 'Costa do Marfim')
     , ('188', 'CR', 'CRI', 'Costa Rica')
     , ('191', 'HR', 'HRV', 'Croácia')
     , ('192', 'CU', 'CUB', 'Cuba')
     , ('208', 'DK', 'DNK', 'Dinamarca')
     , ('262', 'DJ', 'DJI', 'Djibouti')
     , ('212', 'DM', 'DMA', 'Dominica')
     , ('818', 'EG', 'EGY', 'Egito')
     , ('222', 'SV', 'SLV', 'El Salvador')
     , ('784', 'AE', 'ARE', 'Emirados Árabes Unidos')
     , ('218', 'EC', 'ECU', 'Equador')
     , ('232', 'ER', 'ERI', 'Eritreia')
     , ('703', 'SK', 'SVK', 'Eslováquia')
     , ('705', 'SI', 'SVN', 'Eslovénia')
     , ('724', 'ES', 'ESP', 'Espanha')
     , ('840', 'US', 'USA', 'Estados Unidos da América')
     , ('233', 'EE', 'EST', 'Estónia')
     , ('231', 'ET', 'ETH', 'Etiópia')
     , ('242', 'FJ', 'FJI', 'Fiji')
     , ('608', 'PH', 'PHL', 'Filipinas')
     , ('246', 'FI', 'FIN', 'Finlândia')
     , ('250', 'FR', 'FRA', 'França')
     , ('266', 'GA', 'GAB', 'Gabão')
     , ('270', 'GM', 'GMB', 'Gâmbia')
     , ('288', 'GH', 'GHA', 'Gana')
     , ('268', 'GE', 'GEO', 'Geórgia')
     , ('292', 'GI', 'GIB', 'Gibraltar')
     , ('826', 'GB', 'GBR', 'Grã-Bretanha')
     , ('308', 'GD', 'GRD', 'Granada')
     , ('300', 'GR', 'GRC', 'Grécia')
     , ('304', 'GL', 'GRL', 'Gronelândia')
     , ('312', 'GP', 'GLP', 'Guadalupe')
     , ('316', 'GU', 'GUM', 'Guam')
     , ('320', 'GT', 'GTM', 'Guatemala')
     , ('831', 'GG', 'GGY', 'Guernsey')
     , ('328', 'GY', 'GUY', 'Guiana')
     , ('254', 'GF', 'GUF', 'Guiana Francesa')
     , ('324', 'GN', 'GIN', 'Guiné')
     , ('226', 'GQ', 'GNQ', 'Guiné Equatorial')
     , ('624', 'GW', 'GNB', 'Guiné-Bissau')
     , ('332', 'HT', 'HTI', 'Haiti')
     , ('528', 'NL', 'NLD', 'Holanda')
     , ('340', 'HN', 'HND', 'Honduras')
     , ('344', 'HK', 'HKG', 'Hong Kong')
     , ('348', 'HU', 'HUN', 'Hungria')
     , ('887', 'YE', 'YEM', 'Iémen')
     , ('074', 'BV', 'BVT', 'Ilha Bouvet')
     , ('833', 'IM', 'IMN', 'Ilha de Man')
     , ('162', 'CX', 'CXR', 'Ilha do Natal')
     , ('612', 'PN', 'PCN', 'Ilha Pitcairn')
     , ('638', 'RE', 'REU', 'Ilha Reunião')
     , ('248', 'AX', 'ALA', 'Ilhas Aland')
     , ('136', 'KY', 'CYM', 'Ilhas Cayman')
     , ('166', 'CC', 'CCK', 'Ilhas dos Cocos')
     , ('174', 'KM', 'COM', 'Ilhas Comores')
     , ('184', 'CK', 'COK', 'Ilhas Cook')
     , ('234', 'FO', 'FRO', 'Ilhas Faroé')
     , ('238', 'FK', 'FLK', 'Ilhas Falkland')
     , ('239', 'GS', 'SGS', 'Ilhas Geórgia do Sul e Sandwich do Sul')
     , ('334', 'HM', 'HMD', 'Ilhas Heard e McDonald')
     , ('580', 'MP', 'MNP', 'Ilhas Marianas do Norte')
     , ('584', 'MH', 'MHL', 'Ilhas Marshall')
     , ('581', 'UM', 'UMI', 'Ilhas Menores dos Estados Unidos')
     , ('574', 'NF', 'NFK', 'Ilhas Norfolk')
     , ('690', 'SC', 'SYC', 'Ilhas Seychelles')
     , ('090', 'SB', 'SLB', 'Ilhas Salomão')
     , ('744', 'SJ', 'SJM', 'Ilhas Svalbard e Jan Mayen')
     , ('772', 'TK', 'TKL', 'Ilhas Tokelau')
     , ('796', 'TC', 'TCA', 'Ilhas Turks e Caicos')
     , ('850', 'VI', 'VIR', 'Ilhas Virgens (EUA)')
     , ('092', 'VG', 'VGB', 'Ilhas Virgens (Inglaterra)')
     , ('876', 'WF', 'WLF', 'Ilhas Wallis e Futuna')
     , ('356', 'IN', 'IND', 'índia')
     , ('360', 'ID', 'IDN', 'Indonésia')
     , ('364', 'IR', 'IRN', 'Irão')
     , ('368', 'IQ', 'IRQ', 'Iraque')
     , ('372', 'IE', 'IRL', 'Irlanda')
     , ('352', 'IS', 'ISL', 'Islândia')
     , ('376', 'IL', 'ISR', 'Israel')
     , ('380', 'IT', 'ITA', 'Itália')
     , ('388', 'JM', 'JAM', 'Jamaica')
     , ('392', 'JP', 'JPN', 'Japão')
     , ('832', 'JE', 'JEY', 'Jersey')
     , ('400', 'JO', 'JOR', 'Jordânia')
     , ('296', 'KI', 'KIR', 'Kiribati')
     , ('414', 'KW', 'KWT', 'Kuwait')
     , ('418', 'LA', 'LAO', 'Laos')
     , ('428', 'LV', 'LVA', 'Letónia')
     , ('426', 'LS', 'LSO', 'Lesoto')
     , ('422', 'LB', 'LBN', 'Lbano')
     , ('430', 'LR', 'LBR', 'Libéria')
     , ('434', 'LY', 'LBY', 'Líbia')
     , ('438', 'LI', 'LIE', 'Liechtenstein')
     , ('440', 'LT', 'LTU', 'Lituânia')
     , ('442', 'LU', 'LUX', 'Luxemburgo')
     , ('446', 'MO', 'MAC', 'Macau')
     , ('807', 'MK', 'MKD', 'Macedónia')
     , ('450', 'MG', 'MDG', 'Madagáscar')
     , ('458', 'MY', 'MYS', 'Malásia')
     , ('454', 'MW', 'MWI', 'Malaui')
     , ('462', 'MV', 'MDV', 'Maldivas')
     , ('466', 'ML', 'MLI', 'Mali')
     , ('470', 'MT', 'MLT', 'Malta')
     , ('504', 'MA', 'MAR', 'Marrocos')
     , ('474', 'MQ', 'MTQ', 'Martinica')
     , ('480', 'MU', 'MUS', 'Maurício')
     , ('478', 'MR', 'MRT', 'Mauritânia')
     , ('175', 'YT', 'MYT', 'Mayotte')
     , ('484', 'MX', 'MEX', 'México')
     , ('583', 'FM', 'FSM', 'Micronésia')
     , ('508', 'MZ', 'MOZ', 'Moçambique')
     , ('498', 'MD', 'MDA', 'Moldávia')
     , ('492', 'MC', 'MCO', 'Mónaco')
     , ('496', 'MN', 'MNG', 'Mongólia')
     , ('499', 'ME', 'MNE', 'Montenegro')
     , ('500', 'MS', 'MSR', 'Montserrat')
     , ('104', 'MM', 'MMR', 'Myanmar')
     , ('516', 'NA', 'NAM', 'Namíbia')
     , ('520', 'NR', 'NRU', 'Nauru')
     , ('524', 'NP', 'NPL', 'Nepal')
     , ('558', 'NI', 'NIC', 'Nicarágua')
     , ('562', 'NE', 'NER', 'Níger')
     , ('566', 'NG', 'NGA', 'Nigéria')
     , ('570', 'NU', 'NIU', 'Niue')
     , ('578', 'NO', 'NOR', 'Noruega')
     , ('540', 'NC', 'NCL', 'Nova Caledónia')
     , ('554', 'NZ', 'NZL', 'Nova Zelândia')
     , ('512', 'OM', 'OMN', 'Omã')
     , ('585', 'PW', 'PLW', 'Palau')
     , ('591', 'PA', 'PAN', 'Panamá')
     , ('598', 'PG', 'PNG', 'Papua-Nova Guiné')
     , ('586', 'PK', 'PAK', 'Paquistão')
     , ('600', 'PY', 'PRY', 'Paraguai')
     , ('604', 'PE', 'PER', 'Peru')
     , ('258', 'PF', 'PYF', 'Polinésia Francesa')
     , ('616', 'PL', 'POL', 'Polónia')
     , ('630', 'PR', 'PRI', 'Porto Rico')
     , ('620', 'PT', 'PRT', 'Portugal')
     , ('634', 'QA', 'QAT', 'Qatar')
     , ('404', 'KE', 'KEN', 'Quénia')
     , ('417', 'KG', 'KGZ', 'Quirguistão')
     , ('140', 'CF', 'CAF', 'República Centro-Africana')
     , ('180', 'CD', 'COD', 'República Democrática do Congo')
     , ('214', 'DO', 'DOM', 'República Dominicana')
     , ('203', 'CZ', 'CZE', 'República Checa')
     , ('642', 'RO', 'ROM', 'Roménia')
     , ('646', 'RW', 'RWA', 'Ruanda')
     , ('643', 'RU', 'RUS', 'Rússia')
     , ('732', 'EH', 'ESH', 'Saara Ocidental')
     , ('670', 'VC', 'VCT', 'São Vicente e Granadinas')
     , ('016', 'AS', 'ASM', 'Samoa Americana')
     , ('882', 'WS', 'WSM', 'Samoa Ocidental')
     , ('674', 'SM', 'SMR', 'San Marino')
     , ('654', 'SH', 'SHN', 'Santa Helena')
     , ('662', 'LC', 'LCA', 'Santa Lúcia')
     , ('652', 'BL', 'BLM', 'São Bartolomeu')
     , ('659', 'KN', 'KNA', 'São Cristóvão e Névis')
     , ('663', 'MF', 'MAF', 'São Martim')
     , ('678', 'ST', 'STP', 'São Tomé e Príncipe')
     , ('686', 'SN', 'SEN', 'Senegal')
     , ('694', 'SL', 'SLE', 'Serra Leoa')
     , ('688', 'RS', 'SRB', 'Sérvia')
     , ('702', 'SG', 'SGP', 'Singapura')
     , ('760', 'SY', 'SYR', 'Síria')
     , ('706', 'SO', 'SOM', 'Somália')
     , ('144', 'LK', 'LKA', 'Sri Lanka')
     , ('666', 'PM', 'SPM', 'São Pedro e Miquelon')
     , ('748', 'SZ', 'SWZ', 'Suazilândia')
     , ('736', 'SD', 'SDN', 'Sudão')
     , ('752', 'SE', 'SWE', 'Suécia')
     , ('756', 'CH', 'CHE', 'Suíça')
     , ('740', 'SR', 'SUR', 'Suriname')
     , ('762', 'TJ', 'TJK', 'Tajiquistão')
     , ('764', 'TH', 'THA', 'Tailândia')
     , ('158', 'TW', 'TWN', 'Taiwan')
     , ('834', 'TZ', 'TZA', 'Tanzânia')
     , ('086', 'IO', 'IOT', 'Território Britânico do Oceano índico')
     , ('260', 'TF', 'ATF', 'Território do Sul da França')
     , ('275', 'PS', 'PSE', 'Território Palestino Ocupado')
     , ('626', 'TP', 'TMP', 'Timor Leste')
     , ('768', 'TG', 'TGO', 'Togo')
     , ('776', 'TO', 'TON', 'Tonga')
     , ('780', 'TT', 'TTO', 'Trinidad e Tobago')
     , ('788', 'TN', 'TUN', 'Tunísia')
     , ('795', 'TM', 'TKM', 'Turcomenistão')
     , ('792', 'TR', 'TUR', 'Turquia')
     , ('798', 'TV', 'TUV', 'Tuvalu')
     , ('804', 'UA', 'UKR', 'Ucrânia')
     , ('800', 'UG', 'UGA', 'Uganda')
     , ('858', 'UY', 'URY', 'Uruguai')
     , ('860', 'UZ', 'UZB', 'Usbequistão')
     , ('548', 'VU', 'VUT', 'Vanuatu')
     , ('336', 'VA', 'VAT', 'Vaticano')
     , ('862', 'VE', 'VEN', 'Venezuela')
     , ('704', 'VN', 'VNM', 'Vietname')
     , ('894', 'ZM', 'ZMB', 'Zâmbia')
     , ('716', 'ZW', 'ZWE', 'Zimbabué');

insert
  into pje.tb_estado (id_pais, cd_uf, ds_estado)
values (31, 'AC', 'Acre')
     , (31, 'AL', 'Alagoas')
     , (31, 'AP', 'Amapá')
     , (31, 'AM', 'Amazonas')
     , (31, 'BA', 'Bahia')
     , (31, 'CE', 'Ceará')
     , (31, 'DF', 'Brasília')
     , (31, 'ES', 'Espírito Santo')
     , (31, 'GO', 'Goiás')
     , (31, 'MA', 'Maranhão')
     , (31, 'MT', 'Mato Grosso')
     , (31, 'MS', 'Mato Grosso do Sul')
     , (31, 'MG', 'Minas Gerais')
     , (31, 'PA', 'Pará')
     , (31, 'PB', 'Paraíba')
     , (31, 'PR', 'Paraná')
     , (31, 'PE', 'Pernambuco')
     , (31, 'PI', 'Piauí')
     , (31, 'RJ', 'Rio de Janeiro')
     , (31, 'RN', 'Rio Grande do Norte')
     , (31, 'RS', 'Rio Grande do Sul')
     , (31, 'RO', 'Rondônia')
     , (31, 'RR', 'Roraima')
     , (31, 'SC', 'Santa Catarina')
     , (31, 'SP', 'São Paulo')
     , (31, 'SE', 'Sergipe')
     , (31, 'TO', 'Tocantins');
